#BOOTLOADER = atmel-dfu

RGBLIGHT_ENABLE = no       # Enable keyboard RGB underglow
AUDIO_ENABLE = no          # Audio output
MUSIC_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
BACKLIGHT_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
RGB_MATRIX_ENABLE = no
SWAP_HANDS_ENABLE = no
LTO_ENABLE = yes
OLED_DRIVER = SSD1306

LEADER_ENABLE = no
COMBO_ENABLE = yes
OLED_ENABLE = yes
OLED_FONT_ENABLE = yes
WPM_ENABLE = yes
